import pandas as pd
import numpy as np
import os

# ==========================================
# 1. HELPER FUNCTIONS (Manual Indicators)
# ==========================================
def calculate_rsi(series, period=14):
    """
    Manually calculates RSI using Wilder's Smoothing (matches pandas_ta).
    """
    delta = series.diff()
    gain = (delta.where(delta > 0, 0))
    loss = (-delta.where(delta < 0, 0))

    # Use Exponential Moving Average (Wilder's method uses alpha=1/n)
    # com=(period-1) is mathematically equivalent to alpha=1/period for ewm
    avg_gain = gain.ewm(com=period-1, min_periods=period).mean()
    avg_loss = loss.ewm(com=period-1, min_periods=period).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def calculate_sma(series, period=50):
    """
    Manually calculates Simple Moving Average.
    """
    return series.rolling(window=period).mean()

def calculate_atr(df, period=14):
    """
    Manually calculates Average True Range (ATR).
    """
    high = df['high']
    low = df['low']
    close = df['close']
    prev_close = close.shift(1)
    
    # True Range Calculation
    tr1 = high - low
    tr2 = (high - prev_close).abs()
    tr3 = (low - prev_close).abs()
    
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    
    # ATR using Wilder's Smoothing (EMA)
    atr = tr.ewm(com=period-1, min_periods=period).mean()
    return atr

# ==========================================
# 2. MAIN CONVERTER
# ==========================================
def main():
    print("="*60)
    print("🐴 TROJAN HORSE CONVERTER (No-Dependency Version)")
    print("   Injecting Indicators into OHLC without pandas_ta")
    print("="*60)

    # 1. Input
    while True:
        path = input("\nEnter path to ORIGINAL PROCESSED CSV (Prices):\n>> ").strip().strip('"').strip("'")
        if os.path.exists(path): break
        print("❌ File not found.")

    save_dir = input("\nEnter save folder path:\n>> ").strip().strip('"').strip("'")
    if not os.path.exists(save_dir):
        try: os.makedirs(save_dir)
        except: pass

    print(f"\nProcessing {os.path.basename(path)}...")
    df = pd.read_csv(path)
    
    # Clean headers
    df.columns = df.columns.str.strip()
    
    # 2. CALCULATION ENGINE
    print("...Calculating Advanced Indicators (Manual)")
    
    # A. CLOSE (Target) -> Robust Log Return
    # Target: The actual price movement we want to predict
    df['target_close'] = np.log(df['close'] / df['close'].shift(1))
    
    # B. OPEN -> RSI (Scaled 0.0 to 1.0)
    # Context: Is the market Overbought (0.8) or Oversold (0.2)?
    rsi_series = calculate_rsi(df['close'], period=14)
    df['trojan_open'] = rsi_series / 100.0
    
    # C. HIGH -> Distance to SMA 50
    # Context: Trend Extension (How far are we stretched from the mean?)
    sma_series = calculate_sma(df['close'], period=50)
    # Avoid division by zero
    df['trojan_high'] = (df['close'] - sma_series) / (sma_series.replace(0, np.nan))
    
    # D. LOW -> Volatility (ATR Normalized)
    # Context: Fear / Expected Move Size
    atr_series = calculate_atr(df, period=14)
    # Normalize ATR by price so it becomes a percentage (like 0.01 for 1%)
    df['trojan_low'] = atr_series / df['close']
    
    # E. VOLUME -> Relative Volume (Log Ratio)
    # Context: Conviction (Is volume higher than the 20-period average?)
    vol_ma = df['volume'].rolling(20).mean()
    df['trojan_volume'] = np.log((df['volume'] + 1) / (vol_ma + 1))

    # 3. OVERWRITE COLUMNS (The Trojan Move)
    df_final = pd.DataFrame()
    df_final['timestamps'] = df['timestamps']
    
    # Inject the Trojan Features
    df_final['open']   = df['trojan_open']      # RSI (0-1)
    df_final['high']   = df['trojan_high']      # Trend Dist
    df_final['low']    = df['trojan_low']       # Volatility
    df_final['close']  = df['target_close']     # Log Return (Target)
    df_final['volume'] = df['trojan_volume']    # Rel Volume
    
    # 4. CLEANUP
    # Drop NaNs generated by indicators (first 50 rows due to SMA)
    df_final.dropna(inplace=True)
    
    # Replace any Infinite values with 0
    cols = ['open', 'high', 'low', 'close', 'volume']
    df_final[cols] = df_final[cols].replace([np.inf, -np.inf], 0)
    
    # 5. SAVE
    name_part = os.path.splitext(os.path.basename(path))[0]
    output_path = os.path.join(save_dir, f"{name_part}_trojan_features.csv")
    
    df_final.to_csv(output_path, index=False)
    
    print("\n" + "="*60)
    print("✅ SUCCESS! The Trojan Horse is ready.")
    print("="*60)
    print(f"File: {output_path}")
    print("\nDATA MAPPING:")
    print(" 'open'   --> RSI (0.0 - 1.0)")
    print(" 'high'   --> Distance to 50 SMA")
    print(" 'low'    --> Volatility (ATR %)")
    print(" 'close'  --> Log Return (Target)")
    print(" 'volume' --> Relative Volume")
    print("="*60)

if __name__ == "__main__":
    main()